apiVersion: v1
kind: ConfigMap
metadata:
  name: php-cm
  labels:
    tier: backend
data:
  APP_NAME: "Laravel_EDU"
  APP_ENV: "local"
  APP_DEBUG: "true"
  APP_URL: "http://arch.homework"
  LOG_CHANNEL: "stack"
  LOG_DEPRECATIONS_CHANNEL: "null"
  LOG_LEVEL: "debug"
#  DB_HOST: "postgres"
  DB_HOST: "k4-postgresql"
  DB_PORT: "5432"